# Generated by Django 5.1.4 on 2024-12-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
