# Generated by Django 5.1.4 on 2024-12-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_box_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('target', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('dumped', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='untitled', max_length=128),
        ),
    ]
