# Generated by Django 5.1.4 on 2024-12-21 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_shorturl_note_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='path',
            new_name='id',
        ),
        migrations.AddField(
            model_name='note',
            name='dumped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
